version: 0.0
os: linux
files:
  - source: /Dockerfile
    destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: /script1
      timeout: 300
      runas: root
    - location: /script2
      timeout: 300
      runas: root

